export const ODS_LIST = [
  { value: 1, label: "ODS 1 - Fin de la pobreza" },
  { value: 2, label: "ODS 2 - Hambre cero" },
  { value: 3, label: "ODS 3 - Salud y bienestar" },
  { value: 4, label: "ODS 4 - Educación de calidad" },
  { value: 5, label: "ODS 5 - Igualdad de género" },
  { value: 6, label: "ODS 6 - Agua limpia y saneamiento" },
  { value: 7, label: "ODS 7 - Energía asequible y no contaminante" },
  { value: 8, label: "ODS 8 - Trabajo decente y crecimiento económico" },
  { value: 9, label: "ODS 9 - Industria, innovación e infraestructura" },
  { value: 10, label: "ODS 10 - Reducción de las desigualdades" },
  { value: 11, label: "ODS 11 - Ciudades y comunidades sostenibles" },
  { value: 12, label: "ODS 12 - Producción y consumo responsables" },
  { value: 13, label: "ODS 13 - Acción por el clima" },
  { value: 14, label: "ODS 14 - Vida submarina" },
  { value: 15, label: "ODS 15 - Vida de ecosistemas terrestres" },
  { value: 16, label: "ODS 16 - Paz, justicia e instituciones sólidas" },
  { value: 17, label: "ODS 17 - Alianzas para lograr los objetivos" },
];