export const ODS_LIST = [
  { value: 1, label: "ODS 1 - End to poverty" },
  { value: 2, label: "ODS 2 - Zero hunger" },
  { value: 3, label: "ODS 3 - Health and wellness" },
  { value: 4, label: "ODS 4 - Quality education" },
  { value: 5, label: "ODS 5 - Gender equality" },
  { value: 6, label: "ODS 6 - Clean water and sanitation" },
  { value: 7, label: "ODS 7 - Affordable and clean energy" },
  { value: 8, label: "ODS 8 - Decent work and economic growth" },
  { value: 9, label: "ODS 9 - Industry, innovation and infrastructure" },
  { value: 10, label: "ODS 10 - Reduction of inequalities" },
  { value: 11, label: "ODS 11 - Cities and communities sustainable" },
  { value: 12, label: "ODS 12 - Production and responsable consume" },
  { value: 13, label: "ODS 13 - Clime action" },
  { value: 14, label: "ODS 14 - Underwater life" },
  { value: 15, label: "ODS 15 - Earth ecosystems life" },
  { value: 16, label: "ODS 16 - Peace, justices and solid instructions" },
  { value: 17, label: "ODS 17 - Alliance to reach objectives" },
];